services:
  runner:
    image: dataprocessor/hdp-runner:v0.0.1
    env_file:
      - .env
    volumes:
      - ./input.json:/hdp-runner/input.json
      - ./output.json:/hdp-runner/output.json
      - ./cairo.pie:/hdp-runner/cairo.pie
      - ./request.json:/hdp-runner/request.json
