[package]
name = "custom_module"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.3"
hdp_cairo = { git = "https://github.com/HerodotusDev/hdp-cairo.git", rev = "ba9dba20984bdd09a38dedbf07daa2b7e994b58a" }

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
